# Generated by Django 4.2.4 on 2024-01-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
