# Generated by Django 4.2.4 on 2023-09-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_categori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categori',
            new_name='category',
        ),
    ]
